StudentPortal/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentLibrary.Models;
using System.Text;
using StudentLibrary.classes;

namespace StudentPortal.Controllers
{
    public class StudentController : BaseController
    {
        StudentRegistrationEntities ab = new StudentRegistrationEntities();
        clsCommon objCommon = new clsCommon();
        clsStudent objStudent = new clsStudent();


        [HttpGet]

        public ActionResult Edit(int id)
        {
            var item = ab.StdRegistrations.FirstOrDefault(x => x.Sid == id);
            return View("Edit", item);
        }
        [HttpPost]
        public ActionResult Edit(StdRegistration model)
        {
            model.Password = objCommon.GenerateMD5(model.Password);
             if (model.Sid > 0)
             {
                objStudent.EditForm(model);
                return RedirectToAction("StudentRecord");
             }
            return View();
             }
                
        [HttpGet]
        public ActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddStudent(StdRegistration model)

        {
            int studentID = 0;
            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
             objStudent.SaveStudent(model);    
            {
                return RedirectToAction("StudentRecord");
            }
        }
        public ActionResult StudentRecord()
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }

            var item = ab.StdRegistrations.ToList();
            ViewBag.List = item;
            return View();
        }
        public ActionResult Delete(int id)
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            objStudent.DeleteRecord(id);
            return RedirectToAction("StudentRecord");
        }
        public ActionResult ProfileView(int id)
        {
            
            var item = ab.StdRegistrations.Where(x => x.Sid == id).FirstOrDefault();
            ViewBag.item = item;
            var item1 = ab.v_StudentClass.Where(x => x.StudentId == id).ToList();  
            ViewBag.item1 = item1;
            ViewBag.StudentID = id;
            return View();
        }
        public ActionResult Classes()
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            var item = ab.Classes.ToList();
            ViewBag.item = item;
            return View();
        }
        [HttpGet]
        public ActionResult AddClass()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddClass(Class model)
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        
            return RedirectToAction("Classes");
        }
        public ActionResult Delete1(int id)
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }

            var item = ab.Classes.Where(x => x.ClassId == id).First();
            ab.Classes.Remove(item);
            ab.SaveChanges();
            return RedirectToAction("Classes");
        }
        [HttpGet]
        public ActionResult StudentClass(int StudentID)
        {
            ViewBag.AllClasses = ab.Classes.Select(x => new SelectListItem { Text = x.ClassName.ToString(), Value = x.ClassId.ToString() }).ToList();
            ViewBag.StudentID = StudentID;
            return View();
        }
        [HttpPost]
        public ActionResult StudentClass(StudentClass model)
        {
            //int ID = 0;
            objStudent.CountClass(model);
            //ID = ab.StudentClasses.Select(x => x.StudentClassId).Max();

            return RedirectToAction("ProfileView", new {id = model.StudentId });
        }
        [HttpGet]
        public ActionResult Edit1(int id)
        {
            var item = ab.Classes.FirstOrDefault(x => x.ClassId == id);
            return View("Edit1", item);

        
        }
        [HttpPost]
        public ActionResult Edit1(Class model)
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            if (model.ClassId > 0)
            {
                var item = ab.Classes.FirstOrDefault(x => x.ClassId == model.ClassId);
                item.ClassName = model.ClassName;
                ab.SaveChanges();
                return RedirectToAction("Classes");
            }
            return View();
        }
        public ActionResult Delete2(int id)
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            var item = ab.StudentClasses.Where(x => x.StudentClassId == id).First();
            ab.StudentClasses.Remove(item);
            ab.SaveChanges();
            return RedirectToAction("StudentRecord");
        }
        [HttpGet]
        public ActionResult Edit2(int id, int StudentId)
        {
            var item = ab.StudentClasses.FirstOrDefault(x => x.StudentClassId == id);
            ViewBag.AllClasses = ab.Classes.Select(x => new SelectListItem { Text = x.ClassName.ToString(), Value = x.ClassId.ToString() }).ToList();
            ViewBag.StudentId = StudentId;

            return View("Edit2", item);


        }
        [HttpPost]
        public ActionResult Edit2(StudentClass model)
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            objStudent.ClassEdit(model);
            if (model.StudentId > 0)
            {             
                return RedirectToAction("StudentRecord");
            }
            return View();
        }
    }
}

StudentPortal/Views/Student/AddClass.cshtml
@model StudentLibrary.Models.Class
@{
    ViewBag.Title = "AddClass";
}

<h2>AddClass</h2>

@using (Html.BeginForm("AddClass", "Student"))
{
    <div class="col-md-2">
       
        @Html.TextBoxFor(m => m.ClassName, new { @class = "form-control", placeholder = "ClassName", required = true })
        <div class="input-group-append">
         
        </div>
    </div>
    <br />
    <button type="submit" value="Submit" class="btn btn-success">Submit</button>

}

StudentPortal/Views/Student/AddStudent.cshtml
@model StudentLibrary.Models.StdRegistration

@{
    ViewBag.Title = "AddStudent";
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/skin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/skin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/skin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Student</b>LTE</a>
        </div>

        @using (Html.BeginForm("AddStudent", "Student"))

        {

            <div class="card">
                <div class="card-body login-card-body">
                    <form action="../../index3.html" method="post">
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control", placeholder = "Firstname" ,required=true})
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control", placeholder = "Lastname", required = true })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Fathername, new { @class = "form-control", placeholder = "Fathername", required = true })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.StudentCnic, new { @class = "form-control", placeholder = "StudentCnic", required = true })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Address", required = true })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email", required = true })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password", required = true })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">

                            </div>
                            <!-- /.col -->

                            <div class="col-4">
                                @Html.HiddenFor(m => m.Sid)
                                <button type="submit" value="Submit" class="btn btn-success">Submit</button>


                            </div>
                            <!-- /.col -->
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
</body>
</html>

StudentPortal/Views/Student/Classes.cshtml
@model StudentLibrary.Models.Class
@{
    ViewBag.Title = "Classes"; 
}

<h2>Classes</h2>
<button type="submit" value="submit" class="btn btn-success" onclick="location.href='@Url.Action("AddClass","Student")'"><i class="plus-square"> Add Class</i></button>
<br /> 

<br />
<table id="tablemodel" class="table table-bordered table-hover table-striped ">
   
    <thead>
     <tr>
           
            <th>ClassName</th>
            <th>Action</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.item)
        {
            <tr>
                      
                <td>@item.ClassName</td>             
                <td>
                    <a href="@Url.Action("Delete1",new { id=item.ClassId })"><i class="btn btn-success"><b>Delete</b> </i></a>
                    <a href="@Url.Action("Edit1",new { id=item.ClassId})"><i class="btn btn-success">Edit</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>

<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
        $('#tablemodel').DataTable({



        });


    </script>

}

StudentPortal/Views/Student/Edit.cshtml
@model StudentLibrary.Models.StdRegistration

@*@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<h2>Student Registration Form</h2>

@using (Html.BeginForm("Edit", "Student"))
{
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Firstname)
                @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Fathername)
                @Html.TextBoxFor(m => m.Fathername, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Address)
                @Html.TextAreaFor(m => m.Address, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Lastname)
                @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.StudentCnic)
                @Html.TextBoxFor(m => m.StudentCnic, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            </div>

            @Html.HiddenFor(m => m.Sid)

            <input type="submit" value="Save Data" class="btn btn-success" />
        </div>

    </div>


}*@


@*<--Add CSS -->*@


@{
    ViewBag.Title = "Edit";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/skin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/skin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/skin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>

        @using (Html.BeginForm("Edit", "Student"))

        {

            <div class="card">
                <div class="card-body login-card-body">
                    <form action="../../index3.html" method="post">
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control", placeholder = "Firstname"  })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control", placeholder = "Lastname" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Fathername, new { @class = "form-control", placeholder = "Fathername" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.StudentCnic, new { @class = "form-control", placeholder = "StudentCnic" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Address" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                  
                                     
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">

                            </div>
                            <!-- /.col -->

                            <div class="col-4">
                                @Html.HiddenFor(m => m.Sid)
                                <button type="submit" value="Save Changes" class="btn btn-success">Submit</button>


                            </div>
                            <!-- /.col -->
                        </div>
                        </form>
                    </div>
                </div>
        }
        </div>
        </body>
</html>

StudentPortal/Views/Student/Edit1.cshtml
@model StudentLibrary.Models.Class
@{
    ViewBag.Title = "Edit1";
}




@using (Html.BeginForm("Edit1", "Student"))
{
    <div class="col-md-2">

        @Html.TextBoxFor(m => m.ClassName, new { @class = "form-control", placeholder = "ClassName", required = true })
        <div class="input-group-append">

        </div>
    </div>
    <br />
    @Html.HiddenFor(m => m.ClassId)
    <button type="submit" value="Submit" class="btn btn-success">Submit</button>

}

StudentPortal/Views/Student/Edit2.cshtml
@model  StudentLibrary.Models.StudentClass
@{
    ViewBag.Title = "Edit2";
}

<h2>Edit2</h2>


@using (Html.BeginForm("Edit2", "Student"))
{
    <input type="hidden" name="StudentId" value="@ViewBag.StudentID" />
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">Class</label>
            @Html.DropDownListFor(Model => Model.ClassId, (IEnumerable<SelectListItem>)ViewBag.AllClasses, "Please Select Class", new { @class = "form-control" })
        </div>
        <br />
        @Html.HiddenFor(m => m.ClassId)
        <button type="submit" value="Submit" class="btn btn-success">Submit</button>
    </div>
}

StudentPortal/Views/Student/ProfileView.cshtml
@model StudentLibrary.Models.StdRegistration
@{
    ViewBag.Title = "ProfileView";
}

<h2 align="center">ProfileView</h2>

<div class="row">
    <div class="col-md-3">

        <img src="~/Content/images/download.jpg" />
        <h5>Student name: @ViewBag.item.Firstname</h5>
        <h5>Last name: @ViewBag.item.Lastname</h5>
        <h5>Father name: @ViewBag.item.Fathername</h5>
        <h5>StudentCnic : @ViewBag.item.StudentCnic</h5>
        <h5>Address : @ViewBag.item.Address</h5>
        <h5>Email: @ViewBag.item.Email</h5>
    </div>
  
    <div class="col-md-9">
        <a href="/Student/StudentClass?StudentID=@ViewBag.StudentID" class="btn btn-primary"> Add </a>
        <br />
        <br />
        <table id="tablemodel" class="table table-bordered table-hover table-striped ">

            <thead>

                <tr>
                    <th>Student Class ID</th>
                    <th>Student Name</th>
                    <th>Class Name</th>
                    <th>Action</th>

                </tr>
            </thead>        
            <tbody>
                @foreach (var item in ViewBag.item1)
            {
                    <tr>
                        <td>@item.StudentClassId</td>
                        <td>@item.Firstname @item.Lastname</td>
                        <td>@item.ClassName</td>


                        <td>
                            <a href="@Url.Action("Delete2",new { id=item.StudentClassId })"><i class="btn btn-success"><b>Delete</b> </i></a>
                            <a href="@Url.Action("Edit2",new { id=item.StudentClassId , StudentId=item.StudentId })"><i class="btn btn-success">Edit</i></a>

                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
        $('#tablemodel').DataTable({



        });


    </script>

}

StudentPortal/Views/Student/StudentClass.cshtml
@model  StudentLibrary.Models.StudentClass
@{
    ViewBag.Title = "StudentClass";

}

<h4>Assign Class</h4>

@using (Html.BeginForm("StudentClass", "Student"))
{
    <input type="hidden" name="StudentId" value="@ViewBag.StudentID" />
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">Class</label>
            @Html.DropDownListFor(Model => Model.ClassId, (IEnumerable<SelectListItem>)ViewBag.AllClasses, "Please Select Class", new { @class = "form-control" })
        </div>
        <br />
        <button type="submit" value="Submit" class="btn btn-success">Submit</button>
    </div>
}

StudentPortal/Views/Student/StudentRecord.cshtml
@model List<StudentLibrary.Models.StdRegistration>
@{
    ViewBag.Title = "StudentRecord";
}

<h2>StudentRecord</h2>
<button type="submit" value="submit" class="btn btn-success" onclick="location.href='@Url.Action("AddStudent","Student")'"><i class="plus-square"> Add  Student</i></button>
<br />
<br />
<table id="tablemodel" class="table table-bordered table-hover table-striped ">

    <thead>

        <tr>
            <th>Sid</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Fathername</th>
            <th>StudentCnic</th>
            <th>Address</th>
            <th>Email</th>
           
            <th>Action</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.List)
        {
            <tr>
                <td>@item.Sid</td>
                <td>@item.Firstname</td>
                <td>@item.Lastname</td>
                <td>@item.Fathername</td>
                <td>@item.StudentCnic</td>
                <td>@item.Address</td>
                <td>@item.Email</td>
           
                <td>
                    <a href="@Url.Action("Delete",new { id=item.Sid })"><i class="btn btn-success"><b>Delete</b> </i></a>
                    <a href="@Url.Action("Edit",new { id=item.Sid})"><i class="btn btn-success">Edit</i></a>
                    <a href="@Url.Action("ProfileView",new { id=item.Sid})"><i class="btn btn-success user-alt">Profile</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>

<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
        $('#tablemodel').DataTable({



        });


    </script>

}