StudentPortal/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentLibrary.Models;
using StudentLibrary.classes;

namespace StudentPortal.Controllers
{
    public class TeacherController : BaseController
    {
        StudentRegistrationEntities ab = new StudentRegistrationEntities();
        clsCommon objCommon = new clsCommon();
        clsTeacher objTeacher = new clsTeacher();


        public ActionResult Teachers()
        {
            int studentID = 0;

            if (!String.IsNullOrEmpty(Convert.ToString(System.Web.HttpContext.Current.Session["Sid"])))
            {
                studentID = Convert.ToInt32(System.Web.HttpContext.Current.Session["Sid"]);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            var item = ab.TeacherRegistrations.ToList();
            ViewBag.List = item;
            return View();
         
        }

        [HttpGet]
        public ActionResult AddTeacher(int id=0 )
        {
            var item = ab.TeacherRegistrations.FirstOrDefault(x => x.Tid == id);
            ViewBag.item = item;
            return View("AddTeacher", item);

           
        }
        [HttpPost]
        public ActionResult AddTeacher(TeacherRegistration model)
        {
            if (model.Tid > 0)
            {
                model.Password = objCommon.GenerateMD5(model.Password);
                objTeacher.EditTeacher(model);
                return RedirectToAction("Teachers");
            }
            else
            {

                model.Password = objCommon.GenerateMD5(model.Password);
                objTeacher.AddTeacher(model);
                return RedirectToAction("Teachers");
            }
        }

        public ActionResult Delete(int id)
        {

            var item = ab.TeacherRegistrations.Where(x => x.Tid == id).First();
            ab.TeacherRegistrations.Remove(item);
            ab.SaveChanges();
            return RedirectToAction("Teachers");
        }
        public ActionResult ProfileViewTeacher(int id)
        {

            var item = ab.TeacherRegistrations.Where(x => x.Tid == id).FirstOrDefault();
            ViewBag.item = item;
            var item1 = ab.v_TeacherAssign.Where(x => x.Tid == id).ToList();
            ViewBag.item1 = item1;
            ViewBag.TeacherId = id;
            return View();
        }
        [HttpGet]
        public ActionResult TeacherClass(int TeacherClassId =0, int TeacherId=0  )
        {
            var item = ab.TeacherAssigns.FirstOrDefault(x => x.TeacherClassId == TeacherClassId);
            ViewBag.AllClasses = ab.Classes.Select(x => new SelectListItem { Text = x.ClassName.ToString(), Value = x.ClassId.ToString() }).ToList();
            ViewBag.TeacherId = TeacherId;
            if (TeacherClassId>0)
            {
                var item1 = ab.TeacherAssigns.FirstOrDefault(x => x.TeacherClassId == TeacherClassId);
                ViewBag.TeacherClassId = TeacherClassId;
                return View(item1);
            }
           
          
            
            return View("TeacherClass",item);
        }
        [HttpPost]
        public ActionResult TeacherClass(TeacherAssign model)
        {
            if (model.TeacherClassId > 0)
            {
                var item = ab.TeacherAssigns.FirstOrDefault(x => x.Tid == model.Tid);
                item.ClassId = model.ClassId;
                item.Tid = model.Tid;
                ab.SaveChanges();
            }
            else
            {
                TeacherAssign obj = new TeacherAssign();
                obj.Tid = model.Tid;
                obj.ClassId = model.ClassId;
                ab.TeacherAssigns.Add(obj);
                ab.SaveChanges();

                //ID = ab.StudentClasses.Select(x => x.StudentClassId).Max();
            }
            return RedirectToAction("ProfileViewTeacher", new { id = model.Tid });
        }
        public ActionResult DeleteTeacherClass(int id)
        {
            var item = ab.TeacherAssigns.Where(x => x.TeacherClassId == id).First();
            ab.TeacherAssigns.Remove(item);
            ab.SaveChanges();
            return RedirectToAction("Teachers");
        }
    }
}

StudentPortal/Views/Teacher/AddTeacher.cshtml
@model StudentLibrary.Models.TeacherRegistration

@{
    ViewBag.Title = "AddTeacher";
    Layout = null;
   
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/skin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/skin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/skin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Teacher</b>LTE</a>
        </div>

        @using (Html.BeginForm("AddTeacher","Teacher"))

        {

            <div class="card">
                <div class="card-body login-card-body">
                    <form action="../../index3.html" method="post">
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.TeacherName, new { @class = "form-control", placeholder = "TeacherName" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.TeacherCnic, new { @class = "form-control", placeholder = "TeacherCnic" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Address" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">

                            </div>
                            <!-- /.col -->

                            <div class="col-4">
                                @Html.HiddenFor(x => x.Tid)
                                <button type="submit" value="Submit" class="btn btn-success">Submit</button>


                            </div>
                            <!-- /.col -->
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
</body>
</html>

StudentPortal/Views/Teacher/EditTeacherClass.cshtml
@model  StudentLibrary.Models.TeacherAssign
@{
    ViewBag.Title = "EditTeacherClass";
}

@using (Html.BeginForm("EditTeacherClass", "Teacher"))
{
    <input type="hidden" name="Tid" value="@ViewBag.TeacherId" />
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">Class</label>
            @Html.DropDownListFor(Model => Model.ClassId, (IEnumerable<SelectListItem>)ViewBag.AllClasses, "Please Select Class", new { @class = "form-control" })
        </div>
        <br />
        @Html.HiddenFor(m =>m.ClassId)
        <button type="submit" value="Submit" class="btn btn-success">Submit</button>
    </div>
}

StudentPortal/Views/Teacher/ProfileViewTeacher.cshtml
@model StudentLibrary.Models.TeacherRegistration
@{
    ViewBag.Title = "ProfileViewTeacher";
}

<h2 align="center">Teacher Profile View</h2>

<div class="row">
    <div class="col-md-3">
        <img src="~/Content/images/download.jpg" />
        <h5>TeacherName: @ViewBag.item.TeacherName</h5>
        <h5>TeacherCnic: @ViewBag.item.TeacherCnic</h5>
        <h5>Address: @ViewBag.item.Address</h5>
        <h5>Email : @ViewBag.item.Email</h5>

    </div>


   <div class="col-md-9">
       <a href="/Teacher/TeacherClass?TeacherId=@ViewBag.TeacherId" class="btn btn-primary"> Add </a>
        <br />
        <br />
        <table id="tablemodel" class="table table-bordered table-hover table-striped ">

            <thead>

                <tr>
                    <th>TeacherClassId</th>
                    <th>Teacher Name</th>
                    <th>Class Name</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.item1)
            {
                    <tr>
                        <td>@item.TeacherClassId</td>
                         <td>@item.TeacherName</td>
                        <td>@item.ClassName</td>


                        <td>
                            <a href="@Url.Action("DeleteTeacherClass",new { id=item.TeacherClassId })"><i class="btn btn-success"><b>Delete</b> </i></a>
                            <a href="@Url.Action("TeacherClass",new { TeacherClassId=item.TeacherClassId, TeacherId=@ViewBag.TeacherId})"><i class="btn btn-success">Edit</i></a>

                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
        $('#tablemodel').DataTable({



        });


    </script>

}

StudentPortal/Views/Teacher/TeacherClass.cshtml
@model StudentLibrary.Models.TeacherAssign

@{
    ViewBag.Title = "TeacherClass";
}

<h2>TeacherClass</h2>

@using (Html.BeginForm("TeacherClass", "Teacher"))
{
    <input type="hidden" name="Tid" value="@ViewBag.TeacherId " />
    <div class="col-md-6">
        <div class="form-group">
            <label class="control-label">Class</label>
            @Html.DropDownListFor(Model => Model.ClassId, (IEnumerable<SelectListItem>)ViewBag.AllClasses, "Please Select Class", new { @class = "form-control" })
        </div>
        <br />
        @Html.HiddenFor(m => m.TeacherClassId)
        <button type="submit" value="Submit" class="btn btn-success">Submit</button>
    </div>
}

StudentPortal/Views/Teacher/Teachers.cshtml
@model  StudentLibrary.Models.TeacherRegistration
@{
    ViewBag.Title = "Teachers";
}

<h2>TeacherRecord</h2>
<button type="submit" value="submit" class="btn btn-success" onclick="location.href='@Url.Action("AddTeacher","Teacher")'"><i class="plus-square"> Add  Teacher</i></button>
<br />
<br />
<table id="tablemodel" class="table table-bordered table-hover table-striped ">

    <thead>

        <tr>
         
            <th>TeacherName</th>
            <th>TeacherCnic</th>
            <th>address</th>
            <th>Email</th>
           

            <th>Action</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.List)
        {
            <tr>
                
                <td>@item.TeacherName</td>
                <td>@item.TeacherCnic</td>
                <td>@item.Address</td>
                <td>@item.Email</td>    

                <td>
                    <a href="@Url.Action("Delete",new { id=item.Tid })"><i class="btn btn-success"><b>Delete</b> </i></a>
                    <a href="@Url.Action("AddTeacher",new { id=item.Tid})"><i class="btn btn-success">Edit</i></a>
                    <a href="@Url.Action("ProfileViewTeacher",new { id=item.Tid})"><i class="btn btn-success user-alt">Profile</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>

<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
        $('#tablemodel').DataTable({



        });


    </script>

}